l_english:
 PRODUCTION_PRODUCTION_LABEL:0 "생산"
 PRODUCTION_EQUIPMENTPOOL_LABEL:0 "재고"
 PRODUCTION_EFFICIENCY_LABEL:0 "§T효율§!"
 PRODUCTION_EQUIPMENT_LABEL:0 "장비"
 PRODUCTION_ADJUSTERS_LABEL:0 "조정"
 PRODUCTION_MATERIALS_LABEL:0 "자재"
 PRODUCTION_FACTORIES_LABEL:0 "공장"
 PRODUCTION_OPERATIONAL_ARMS_FACTORIES_LABEL:0 "군수 공장"
 PRODUCTION_OPERATIONAL_DOCKYARDS_LABEL:0 "해군 조선소"
 PRODUCTION_OPERATIONAL_FACTORIES_LABEL:0 "민간 공장"
 PRODUCTION_OPERATIONAL_DOCKYARDS_LABEL_SHORT:0 "조선소"
 PRODUCTION_AVAILABLE_ARMS_FACTORIES_LABEL:0 "사용 가능한 군수공장"
 PRODUCTION_AVAILABLE_DOCKYARDS_LABEL:0 "사용 가능한 조선소"
 PRODUCTION_AVAILABLE_FACTORIES_LABEL:0 "사용 가능한 민간공장"
 PRODUCTION_OPERATIONAL_FACTORIES_VALUE:0 "$VALUE$/$TOT$"
 PRODUCTION_MILITARY_LABEL:0 "§T육군 & 공군 장비§!"
 PRODUCTION_NAVAL_LABEL:0 "§T해군 장비§!"
 PRODUCTION_BUILDINGS_LABEL:0 "§TBuildings construction§!"
 PRODUCTION_PRODUCING_DAILY:0 "매일 $AMOUNT$"
 PRODUCTION_PRODUCING_WEEKLY:0 "매주 $AMOUNT$"
 PRODUCTION_PRODUCING_MONTHLY:0 "매월 $AMOUNT$"
 PRODUCTION_PRODUCING_YEARLY:0 "매년 $AMOUNT$"
 PRODUCTION_PRODUCING_ETA_DATE:0 "Next complete: $DATE$"
 PRODUCTION_REPAIRING_ETA_DATE:0 "Reparation complete: $DATE$"
 PRODUCTION_PRODUCING_ETA_DAYS:0 "$AMOUNT$일 내"
 PRODUCTION_PRODUCING_ETA_WEEKS:0 "$AMOUNT$주 내"
 PRODUCTION_PRODUCING_ETA_MONTHS:0 "$AMOUNT$월 내"
 PRODUCTION_PRODUCING_ETA_YEARS:0 "$AMOUNT$년 내"
 PRODUCTION_PRODUCING_NEVER:1 "§RNever§!"
 PRODUCTION_PRODUCING_NO_FACTORIES:0 "§R할당된 공장 없음§!"
 PRODUCTION_PRODUCING_NONE:0 "§R생산 없음§!"
 PRODUCTION_CAN_NOT_DEPLOY:0 "§R배치할 수 없음§!"
 PRODUCTION_CAN_NOT_DEPLOY_MANPOWER:0 "인력 부족"
 PRODUCTION_INCREASE_PRIORITY_LABEL:0 "§G클릭으로 §H우선권 증가§!.\nShift+클릭으로 §H최고 우선권 주기§!.§!"
 PRODUCTION_DECREASE_PRIORITY_LABEL:0 "§G클릭으로 §H우선권 감소§!.\nShift+클릭으로 §H최하 우선권 주기§!.§!"
 PRODUCTION_PRIORITY_DELAYED:0 "우선권이 높은 생산라인은 우선권이 낮은 생산라인보다 자원을 먼저 사용합니다."
 PRODUCTION_EFFICIENCY:0 "£prod_eff  §T생산 효율: $AMOUNT|H2%$§!"
 PRODUCTION_EFFICIENCY_MOD:0 "£prod_eff §T생산 효율: $AMOUNT|Y2%$§!\n"
 PRODUCTION_EFFICIENCY_WITH_GAIN:2 "£prod_eff  §T생산 효율: $AMOUNT|H2%$§! (하루 $GAIN|H3%$)"
 PRODUCTION_EFFICIENCY_DESC:0 "§TAverage Factory Production Efficiency.\nProduction Efficiency Increases by $VALUE|H=2$%/unit produced split evenly on active Factories.§!"
 PRODUCTION_RESOURCE_PENALTY:0 "§TLack of resources: $AMOUNT|R2%$§!"
 PRODUCTION_ASSIGN_EQUIPMENT:0 "§T생산할 장비를 선택하세요.§!"
 PRODUCTION_MATERIALS_OIL:0 "석유"
 PRODUCTION_MATERIALS_ALUMINIUM:0 "알루미늄"
 PRODUCTION_MATERIALS_RUBBER:0 "고무"
 PRODUCTION_MATERIALS_CHROMIUM:0 "크로뮴"
 PRODUCTION_MATERIALS_STEEL:0 "강철"
 PRODUCTION_MATERIALS_TUNGSTEN:0 "텅스텐"
 PRODUCTION_MATERIAL_VAL:0 "$VALUE|0H$"
 PRODUCTION_VEHICLES_BUTTON:0 "기갑 차량 생산"
 PRODUCTION_VEHICLES_BUTTON_DISABLED:0 "기갑 차량이 §R발명되지 않았습니다§!!"
 PRODUCTION_VEHICLES_BUTTON_NO_FACTORIES_DISABLED:0 "군수 공장이 §R없습니다§!!"
 PRODUCTION_INFANTRY_BUTTON:0 "보병 & 포병 장비 생산"
 PRODUCTION_INFANTRY_BUTTON_DISABLED:0 "보병 & 포병 장비가 §R발명되지 않았습니다§!!"
 PRODUCTION_INFANTRY_BUTTON_NO_FACTORIES_DISABLED:0 "군수 공장이 §R없습니다§!!"
 PRODUCTION_AIRCRAFT_BUTTON:0 "항공기 생산"
 PRODUCTION_AIRCRAFT_BUTTON_DISABLED:0 "항공기가 §R발명되지 않았습니다§!!"
 PRODUCTION_AIRCRAFT_BUTTON_NO_FACTORIES_DISABLED:0 "군수 공장이 §R없습니다§!!"
 PRODUCTION_SHIPS_BUTTON:0 "선박 생산"
 PRODUCTION_SHIPS_BUTTON_DISABLED:0 "선박이 §R발명되지 않았습니다§!!"
 PRODUCTION_SHIPS_BUTTON_NO_DEPLOY_DISABLED:0 "항구가 §R없습니다§!!"
 PRODUCTION_SHIPS_BUTTON_NO_FACTORIES_DISABLED:0 "조선소가 §R없습니다§!!"
 PRODUCTION_CONSUMER_GOODS_VALUE:0 "$VALUE$"
 PRODUCTION_CONSUMER_GOODS:0 "소비재"
 PRODUCTION_CONSUMER_GOODS_LABEL:0 "§H소비재§!"
 PRODUCTION_CONSUMER_GOODS_DESC:0 "현재 우리 경제 정책에 따라 민간 및 군수 공장 중 $PERCENTAGE|H0%$가 소비재를 생산할 것입니다. 소비재는 민간 공장에서만 생산할 수 있습니다. 남은 민간 공장은 $OPERATIONAL|H$개로 이 중 $TRADE_USABLE|H$개를 무역에 쓸 수 있습니다."
 PRODUCTION_CIV_AND_MIL_FACTORIES:0 "민간 및 군수 공장 수: $KEY|H$"
 PRODUCTION_REQ_CONSUMER_GOODS_FACTORIES:0 "소비재 생산에 필요한 공장 수: $KEY|H$"
 PRODUCTION_MATERIAL_COST_DESC:0 "§T이 생산 라인은 $AMOUNT|0H$의 $MATERIAL|H$을(를) 사용합니다.§!"
 PRODUCTION_MATERIAL_COST_LACKING_DESC:2 "§T최대 효율을 위해 $AMOUNT|0H$이(가) 필요합니다.§!\n생산이 느린 속도로 진행됩니다§!."
 PRODUCTION_LINE_CANCEL:3 "§G클릭으로 이 생산라인 §H취소§!§!\n§GShift+클릭으로 모든 생산라인 §H취소§!§!"
 PRODUCTION_LINE_CANCEL_SHIP_REFIT:0 "§GClick to §RScuttle§! this Ship which is being refit§!"
 PRODUCTION_CREATE_VARIANT:0 "§H파생형 제작§!"
 PRODUCTION_CANCEL_CONSTRUCTION:0 "§T이 건설을 취소.§!"
 PRODUCTION_VARIANT_OBSOLETE_YES:1 "재도입"
 PRODUCTION_VARIANT_OBSOLETE_NO:1 "퇴역"
 PRODUCTION_VARIANT_OBSOLETE_YES_DESC:0 "§G클릭§!으로 이 모델을 재도입해 최신 장비로 표시합니다."
 PRODUCTION_VARIANT_OBSOLETE_NO_DESC:0 "§G클릭§!으로 이 모델을 퇴역해 도태 장비로 표시합니다."
 TRADE_FACTORIES_VALUE:0 "$VALUE$/$TOT$"
 CONFIRMCANCELPRODUCTIONLINE_TITLE:0 "생산라인 취소"
 CONFIRMCANCELPRODUCTIONLINE_DESC:0 "정말 이 생산라인을 §R취소§!합니까?"
 CONFIRMCANCELALLPRODUCTIONLINE_TITLE:0 "모든 생산라인 취소"
 CONFIRMCANCELALLPRODUCTIONLINE_DESC:0 "정말 모든 생산라인을 §R취소§!합니까?"
 CONFIRM_SWITCH_PRODUCTION_MODEL_TITLE:0 "장비 변경"
 CONFIRM_SWITCH_PRODUCTION_MODEL_DESC:0 "Are you sure you want to §Rswitch§! Equipment? This makes you lose $DAYS|R$ days of production."
 CONFIRMCANCELCONSTRUCTION_TITLE:0 "건설 취소"
 CONFIRMCANCELCONSTRUCTION_DESC:0 "정말 $REGION|H$의 $CONSTRUCTION|H$ 건설을 §R취소§!합니까?"
 CONFIRMCANCELCONSTRUCTIONS_TITLE:0 "모든 건설 취소"
 CONFIRMCANCELCONSTRUCTIONS_DESC:0 "정말 모든 건설을 §R취소§!합니까?"
 INFINITY:0 "£infinity_icon"
 PRODUCTION_EQUIPMENT_NEED:0 "Need: $AMOUNT|Y$"
 PRODUCTION_DEPLOY_TO_BASE:0 "Deploy to port: $BASE|H$"
 PRODUCTION_DEPLOY_TO_FLEET:1 "Deploy to task force: $FLEET|H$"
 PRODUCTION_DEPLOY_TO_RESERVE_FLEET_THEATER:1 "Deploy to the Reserve of theater: $THEATER|H$"
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET_INVALID_BASE:0 "Deploy target $FLEET|H$ has no base."
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET:1 "$STATE|H$ 기지에 주둔한 $FLEET|H$ 기동부대에 배치됩니다."
 PRODUCTION_NAVAL_DEPLOYMENT_THEATER:0 "$THEATER|H$ 전역의 $STATE|H$ 기지에 배치됩니다."
 PRODUCTION_NAVAL_DEPLOYMENT_BASE:0 "$STATE|H$ 기지에 배치됩니다."
 PRODUCTION_NAVAL_DEPLOYMENT_INVALID_BASE:0 "No deploy target set."
 PRODUCTION_NAVAL_DEPLOYMENT_NOT_DEPLOYABLE:0 "Not deployable"
 PRODUCTION_NAVAL_DEPLOYMENT_AUTO_DEPLOYMENT:0 "자동"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING:0 "폐기"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING_DESC:0 "No valid base to deploy to. Unit will be scrapped upon completion."
 PRODUCTION_NAVAL_DEPLOYMENT_STOCKPILING:0 "비축 중"
 PRODUCTION_RIGHT_CLICK_TO_ZOOM:0 "§GRight-click to go to province§!"
 PRODUCTION_NAVAL_DEPLOY_LIST:0 "Deploy target"
 WEEKLY_PRODUCTION:0 "Weekly production"
 PRODUCTION_WORKING_FACTORIES:0 "현재 생산라인에 투입된 공장의 양입니다."
 PRODUCTION_WORKING_DOCKYARDS:0 "현재 생산라인에 투입된 조선소의 양입니다."
 PRODUCTION_WORKING_DOCKYARDS_FOR_REPAIRS:0 "현재 함정 수리에 투입된 조선소의 양입니다."
 PRODICTION_MIC_TRANSFERED:0 "$AMOUNT|Y$ of our factories are used by $OVERLORD|Y$."
 PRODICTION_MIC_RECEIVED_FROM_SUBJECT:0 "$AMOUNT|Y$ 군수 공장을 종속국에서 지원받았습니다."
 PRODICTION_MIC_SENT_TO_OVERLORD:0 "$AMOUNT|R$ 군수 공장이 종주국에게 지원되어 우리는 $LEFT|H$을(를) 쓸 수 있습니다."
 PRODICTION_MIC_RECEIVED_FROM_EXILE_DONATIONS:0 "$AMOUNT|Y$ 군수 공장이 우리 국가 내 망명정부에 기부되었습니다."
 PRODUCTION_CIVILIAN_FACTORIES_AVAILABLE:0 "Available for construction: $VALUE|Y$"
 PRODUCTION_CIVILIAN_FACTORIES_CURRENTLY:0 "In Use: $VALUE|R$"
 PRODUCTION_MAX_EFFICIENCY_BASE:0 "Base Cap: $VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_TOT:0 "£prod_eff_cap  생산 효율 한도: $VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_HINT:0 "£prod_eff_cap  Production Efficiency Cap determines the maximum value for your £prod_eff  Production Efficiency. It can be increased by £tech_mod Technologies."
 PRODUCTION_RESOURCES_PER_FACTORY:0 "§HResources per factory to produce:§!"
 PRODUCTION_MATERIAL_NO_WASTE:0 "Line is not wasting any of this resource."
 PRODUCTION_MATERIAL_WASTE:0 "Line is wasting $WASTE|R2$ of this resource."
 PRODUCTION_SPEED:0 "Production speed: $SPEED|Y$"
 PRODUCTION_SPEED_MODIFIERS:0 "§YProduction output modified by:§!"
 INDUSTRIAL_CAPACITY_FACTOR:0 "공장 생산량: $VALUE|Y$"
 INDUSTRIAL_CAPACITY_FACTOR_MODIFIERS:0 "Factory Output modified by:"
 INDUSTRIAL_PROGRESS:0 "$BUILDING|H$ is $PROGRESS|0H$/$COST|0H$ ( $VALUE|0%H$ ) completed."
 INDUSTRIAL_PROGRESS_REPAIR:0 "$BUILDING|H$ repair progress: $PROGRESS|%0H$"
 INDUSTRIAL_BASE_FACTORY_OUTPUT:0 "Base factory output: $VALUE|H$"
 INDUSTRIAL_BASE_SPEED:0 "Output from $FACTORIES|0H$ factories: $VALUE|H$"
 PROD_COST_VALUE:0 "£production_cost  $VALUE$"
 NAVPROD_COST_VALUE:0 "£navprod_cost  $VALUE$"
 PRODUCTION_CIVILIAN_FACTORIES_OWNED:0 "Owned: $VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_BORROWED:0 "From exports: +$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_SUBJECTS:0 "From subjects: +$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_MASTER:0 "Given to Overlord: $VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_OTHERS:0 "From other countries: +$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_OTHERS:0 "Given to other countries: $VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_DAMAGED:0 "Damaged: $VAL|R$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED:2 "$VALUE|0Y$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_FILLED:1 "$AMOUNT|0G$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_UPGRADE:1 "$VALUE|0Y$"
 PRODUCTION_EQUIPMENT_DAILY_BALANCE:0 "일일 비축량: $VALUE|=2Y$"
 PRODUCTION_EQUIPMENT_FILL_ESTIMATION:0 "With current daily balance we will §YFill§! our needs in $VALUE|0Y$ Days."
 PRODUCTION_EQUIPMENT_FILLED:0 "현재 필요량이 §G충족§!되었습니다."
 PRODUCTION_EQUIPMENT_LOSSES:0 "어제 $VALUE|R$ 만큼 잃었습니다."
 PROD_LINE_PLANE_DEST_RESERVES_DUE_TO_MANPOWER:0 "§Y증원§!할 §H인력§!이 부족해 §Y예비대§!로 이동함"
 PROD_LINE_PLANE_DEST_RESERVES:1 "§Y예비대§!로 이동"
 PROD_LINE_PLANE_DEST_UPGRADING:2 "§Y개선§! 필요"
 PROD_LINE_PLANE_DEST_REINFORCEMENT:2 "§Y증원§! 필요"
 PROD_LINE_LAND_DEST_RESERVES:1 "§Y비축§! 중"
 PROD_LINE_LAND_DEST_UPGRADING:2 "§Y개선§! 필요"
 PROD_LINE_LAND_DEST_REINFORCEMENT:2 "§Y증원§! 필요"
 CONFIRM_REMOVE_BUILDING_LEVEL_TITLE:0 "건물 철거"
 CONFIRM_REMOVE_BUILDING_LEVEL_DESC:0 "정말 이 건물을 §R철거§!합니까?"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_TITLE:0 "건설 취소"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_DESC:0 "정말 이 건설을 §R취소§!합니까?"
 CONFIRM_REMOVE_CONVERSION_LEVEL_TITLE:0 "전환 취소"
 CONFIRM_REMOVE_CONVERSION_LEVEL_DESC:0 "정말 이 전환을 §R취소§!합니까?"
 CONFIRM_ADD_CONVERSION_LEVEL_TITLE:0 "전환 개시"
 CONFIRM_ADD_CONVERSION_LEVEL_DESC:0 "정말 이 건물을 §R전환§!합니까?"
 PRODUCTION_EFFICIENCY_GAIN_BASE:0 "Daily base gain: $VAL|%Y$"
 PRODUCTION_RESOURCE_FACTOR:0 "Lack of resources: $VAL|%+$"
 PRODUCTION_OUTPUT_EXPLAIN:0 "Our $FACTORIES|Y$ £factory_item  Military Factories contribute $OUTPUT|Y$ £production_cost . \n$ITEM|Y$ has a cost of $ITEM_COST|2Y$ £production_cost , which means we can produce $PERTIMEPERIOD$.\n"
 PRODUCTION_OUTPUT_EXPLAIN_NAVAL:0 "Our $FACTORIES|Y$ £naval_factory_icon  Naval Dockyards contribute £navprod_cost $OUTPUT|Y$.\n$ITEM|Y$ has a cost of $ITEM_COST|2Y$ £navprod_cost , which means we can produce $PERTIMEPERIOD$.\n"
 PRODUCTION_UNITS_PER_DAY:0 "$UNITS|Y$ units per day"
 PRODUCTION_UNITS_PER_WEEK:0 "$UNITS|Y$ units per week"
 PRODUCTION_UNITS_PER_MONTH:0 "$UNITS|Y$ units per month"
 PRODUCTION_UNITS_PER_YEAR:0 "$UNITS|Y$ units per year"
 PRODUCTION_FACTORY_ASSIGN_DESC:1 "Click to assign £factory_item $FACTORIES|Y$ §YMilitary Factories§! to this Production Line. This would give a base production output of £production_cost $OUTPUT|Y$ per day.\nThe total output will be affected by §YResources§!, §YProduction Efficiency§! and other §YProduction modifiers§!."
 PRODUCTION_DOCKYARD_ASSIGN_DESC:1 "Click to assign £naval_factory_icon $FACTORIES|Y$ §YNaval Dockyards§! to this Production Line. This will give a base production output of £navprod_cost $OUTPUT|Y$ per day. \nThe total output will be affected by §YResources§! and other §YProduction modifiers§!."
 PRODUCTION_BASE_OUTPUT:0 "Base output: $VALUE|Y$ x $MUL|Y$"
 PRODUCTION_EFF_GAIN_HINT:0 "§YEfficiency gain speed modified by:§!"
 CARRIER_AIR_WING_COMPOSITION_TITLE:0 "Set the default composition of Air Wings for this Carrier"
 CARRIER_AIR_WING_LIMIT_UNDER:0 "$COUNT|Y$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_MATCH:0 "$COUNT|G$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_OVER:0 "$COUNT|R$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_DESC:0 "항공기/항공모함 수용량"
 CARRIER_AIR_WING_LIMIT_DESC_UNDER:0 "§YThe capacity of this carrier won't be fully used§!"
 CARRIER_AIR_WING_LIMIT_DESC_OVER:0 "§RThe capacity of this Carrier will be exceeded and the Air Wings stationed there will suffer a penalty§!"
 CARRIER_AIR_WING_INCREASE:0 "Increase amount\n§GCtrl+click to increase by§! §H5§!\n§GShift+click to increase by§! §H10§!"
 CARRIER_AIR_WING_DECREASE:0 "Decrease amount\n§GCtrl+click to decrease by§! §H5§!\n§GShift+click to decrease by§! §H10§!"
 PRODUCTION_ENTRY_NEW:0 "§GNEW§!"
 PRODUCTION_ENTRY_OUTDATED:0 "§HOUTDATED§!"
 PRODUCTION_LINE_CHANGE:0 "§GClick to §Hchange§! the produced equipment.\nYou will retain some of the Efficiency if you switch to a newer version of the same equipment.\n§!§RYou will lose all progress for this line.§!"
 PRODUCTION_LINE_CHANGE_NAVAL:0 "§GClick to §Hchange§! the produced equipment.\n§!§RYou will lose all progress for this line.§!"
 PRODUCTION_EQUIPMENT_FILTER:0 "Infantry & Artillery Equipment"
 PRODUCTION_ARMOR_FILTER:0 "Armored Vehicles"
 PRODUCTION_AIR_FILTER:0 "Aircraft"
 PRODUCTION_CAPITAL_SHIPS_FILTER:0 "주력함
 PRODUCTION_SCREEN_SHIPS_FILTER:0 "보조함"
 PRODUCTION_OTHER_SHIPS_FILTER:0 "기타 함선"
 PRODUCTION_LACKING_RESOURCES_FILTER:0 "충족된 자원"
 PRODUCTION_STOCKPILING_FILTER:0 "비축 중"
 PRODUCTION_REINFORCING_FILTER:0 "재정비 중"
 PRODUCTION_UPGRADING_FILTER:0 "업그레이드 중"
 PRODUCTION_OUTDATED_FILTER:0 "Up to date models"
 PRODUCTION_REFITTING_FILTER:0 "Refitting"
 PRODUCTION_FILTER_CLICK_TO_HIDE:0 "§GClick§! to §Rhide§! all of this category."
 PRODUCTION_FILTER_CLICK_TO_SHOW:0 "§GClick§! to §Gshow§! all of this category."
 PRODUCTION_FILTER_SHIFTCLICK:1 "\n§GShift+Click§! to §Rhide§! everything else."
 PRODUCTION_FILTER_SHIFTCLICK_AGAIN:0 "\n§GShift+Click§! to §Gshow§! everything again."
 PRODUCTION_FILTER_RIGHTCLICK:0 "\n§GRight Click§! to toggle collapsing all of this category."
 PRODUCTION_FILTER_ARMS_FACTORIES:0 "Military Factories used"
 PRODUCTION_FILTER_DOCKYARDS:0 "Naval Dockyards used"
 PRODUCTION_DRAG_N_DROP:0 "§G드래그 앤 드롭§!으로 §Y우선권§! 변경."
 PRODUCTION_COLLAPSE:1 "§GClick to collapse.§!\n§GCtrl + Click to collapse all of this category.§!\n§GShift + Click to collapse all Production Lines.§!"
 PRODUCTION_EXPAND:1 "§GClick to expand.§!\n§GCtrl + Click to expand all of this category.§!\n§GShift + Click to expand all Production Lines.§!"
 PRODUCTION_FACTORY_SCALE_UP:0 "§GClick§! to scale up to §Y$SCALE$x§! view."
 PRODUCTION_FACTORY_SCALE_DOWN:0 "§GClick§! again to scale down to §Y1x§! view."
 PRODUCTION_ADD_FACTORIES_CLICK:0 "§GClick§! to add §Y+1§!\n§GCtrl + Click§! to add §Y+5§!\n§GShift + Click§! to add §Y+10§!"
 PRODUCTION_SUB_FACTORIES_CLICK:0 "§GClick§! to subtract §Y1§!\n§GCtrl + Click§! to subtract §Y5§!\n§GShift + Click§! to subtract §Y10§!"
 PRODUCTION_ADD_1:0 "§GClick§! to add §Y+1§!"
 PRODUCTION_ADD_5:0 "§GCtrl + Click§! to add §Y+5§!"
 PRODUCTION_ADD_10:0 "§GShift + Click§! to add §Y+10§!"
 PRODUCTION_SUB_1:0 "§GClick§! to subtract §Y1§!"
 PRODUCTION_SUB_5:0 "§GCtrl + Click§! to subtract §Y5§!"
 PRODUCTION_SUB_10:0 "§GShift + Click§! to subtract §Y10§!"
 PRODUCTION_ADD_NAVAL_FACTORIES_CLICK:0 "§GClick§! to add §Y+1§!"
 PRODUCTION_SUB_NAVAL_FACTORIES_CLICK:0 "§GClick§! to subtract §Y1§!"
 PRODUCTION_CLICK_TO_APPEND_OR_INSERT:0 "§GClick§! to append new production line at the end.\n§GShift + Click§! to put a new production line at the top."
 PRODUCTION_NAVAL_DEPLOYMENT_STATE_NAME:0 "$STATE$ ($LVL|Y$)"
 PRODUCTION_LINE_CONVERT_NO_EQUIPMENT_IN_STOCK:0 "§RCurrently there is no equipment in stock that we could use to convert into: $VARIANT|H$§!"
 PRODUCTION_LINE_CONVERT_HEADER:0 "Convert from Stockpile"
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION:0 "Order of conversion:"
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_ENTRY:0 "\n  $NUM|Y2$ of $VARIANT|G$ (§H$TYPE$§!) with cost: "
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_FREE_ENTRY:0 "\n  $NUM|Y2$ of $VARIANT|G$ (§H$TYPE$§!)"
 PRODUCTION_LINE_CONVERT_RESOURCE_COST_ENTRY:0 "§H$NUM$§!£resources_strip|$FRAME$ "
 PRODUCTION_LINE_CONVERT_DESC:1 "Convert from stockpile will use §Houtdated equipment§! or §Hcaptured equipment§! within the stockpile and convert them into modified vehicles requested from the current production line at a reduced cost. This will continue until the stockpile is empty."
 PRODUCTION_LINE_CONVERT_SPEED_TOTAL:1 "Conversion speed: §G+§!$SPD|G%0$"
 PRODUCTION_LINE_CONVERT_SPEED_BASE:0 "Base: $VAL|Y0%$"
 PRODUCTION_LINE_CONVERT_RES_NEED:0 "Resources needed to convert from $NAME|Y$:"
 PRODUCTION_LINE_CONVERT_RES_NEED_ENTRY:0 "\n   £resources_strip|$FRAME$: ($NEW|Y0$-$OLD|G0$)=$SUM|R0$"
 PRODUCTION_LINE_SHIP_NAME_ALLOCATE:0 "이 이름은 아직 사용되지 않았습니다. 추가 버튼 §G클릭§!으로 이 생산라인에 이 이름을 할당합니다."
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL_SIMPLE:0 "§HLicense production§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL:0 "§HLicense production factory output§!\nTotal: $VALUE|+%$\nBreakdown:"
 LICENSED_EQUIPMENT_TECH_SPEED_REDUCTION:1 "§YLicense technology difference§!:\n Base: $BASE|+%$\n Modified total: $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_MODIFIER:1 "§YLicense modifier§!:\n Base: $BASE|+%$\n Modified total: $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NOT_FACTION:0 "§YNot in faction with licensor§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NO_LICENSE:0 "§YNo active license§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_UPGRADE_XP_COST_MODIFIER:0 "Licensed Equipment: $VAL$"
 LICENSED_PURCHASE_CIC_COST:1 "§YThis license costs§!: £civ_factory $AMOUNT|Y$"
 PRODUCTION_NAVAL_REPAIRS_LABEL:0 "Repair Queue"
 PRODUCTION_NAVAL_NAME_LIST:0 "함정 이름"
 PRODUCTION_NAVAL_NAME_LIST_BUTTON_FALLBACK:0 "함정 이름"
 PRODUCTION_NAVAL_NAME_LIST_EMPTY_NOT_ALLOWED:0 "§R이름칸은 비워둘 수 없습니다.§!"
 PRODUCTION_NAVAL_NAME_LIST_TOO_FEW_PRODUCED:0 "§RNames will exceed the number of ships in the production queue.§!"
 PRODUCTION_NAVAL_NAME_LIST_REMOVE:0 "§G클릭§!으로 §H이름 제거§!"
 PRODUCTION_NAVAL_NAME_LIST_NAME_RESERVED:0 "$NAME|H$은(는) 현재 사용 중입니다."
 PRODUCTION_NAVAL_NAME_LIST_ADD_NAME:0 "§GClick§! to name the next $EQUIPMENT|H$ from this line $NAME|H$."
 PRODUCTION_NAVAL_NAME_LIST_BUTTON_NAME:0 "이 생산라인의 다음 $EQUIPMENT|H$은(는) $NAME|H$(으)로 명명됩니다."
 PRODUCTION_NAVAL_NAME_LIST_BUTTON_CLICK:0 "§G클릭§!으로 이름 변경"
 PRODUCTION_SHIP_REFIT_TOTAL_COSTS:0 "§HTotal costs for $COUNT|T$ ships:§!\n"
 PRODUCTION_SHIP_REFIT_BASE_ICCOST:0 "Base Equipment: $ICCOST|H2$"
 PRODUCTION_SHIP_REFIT_MODULE_BUILD_ICCOST:0 "New Modules: $ICCOST|H2$"
 PRODUCTION_SHIP_REFIT_MODULE_CONVERT_ICCOST:0 "Converted Modules: $ICCOST|H2$"
 PRODUCTION_SHIP_REFIT_MODULE_DISMANTLE_ICCOST:0 "Dismantled Modules: $ICCOST|H2$"
 PRODUCTION_SHIP_REFIT_QUICKEST_TIME:0 "With maximum §HDockyards§! assigned, this would take up to $DAYS|H$ days to complete."
 PRODUCTION_SHIP_REFIT_TOOLTIP_DIFF_HEADER:0 "§HEffects of Refitting§!"
 PRODUCTION_SHIP_REFIT_TOOLTIP_FROM_VARIANT_HEADER:0 "From $VARIANT$ ($SHIP_COUNT|H$ selected)"
 PRODUCTION_SHIP_REFIT_TOOLTIP_NO_STAT_CHANGES:0 "no stat changes"
 PRODUCTION_SHIP_REFIT_TOOLTIP_MORE_VARIANTS:0 "and other equipment variants ($SHIP_COUNT|H$ selected)"
 PRODUCTION_SUB_UNIT_FILTER:0 "Show only $SUBUNIT|H$ ($COUNT|H$ match)"
 PRODUCTION_EQUIPMENT_ROLE_NO_FILTER:0 "Show all roles"
 PRODUCTION_EQUIPMENT_ROLE_FILTER:0 "Show only equipment with the role $ROLE|H$"
